name: CI-build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - backend/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9"]

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: severinoapp
          POSTGRES_PASSWORD: password
          POSTGRES_DB: severinoapp_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: List files in the current directory
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install application dependencies
        run: pip install -r nrequirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Initialize Test Database
        run: python init_test_db.py

      - name: Check database connection
        run: |
          psql -h localhost -p 5432 -U severinoapp -d severinoapp_db -c '\l'

      - name: Run application
        run: python3 src/app.py &

      - name: Run tests
        run: pytest
