name: CI-build

on:
  workflow_dispatch: # Permite o disparo manual da workflow
  push:
    branches:
      - develop
    paths:
      - src/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9'] # Definindo múltiplas versões do Python para testar

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: severinoapp_test
          POSTGRES_PASSWORD: severinoapp_test
          POSTGRES_DB: severinoapp_test_db
        ports:
          - 5434:5434
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r nrequirements.txt # Instala as dependências do projeto
      - env:
        DATABASE_URL: postgresql://severinoapp_test:severinoapp_test@localhost:5434/severinoapp_test_db
      - run: pytest # Executa testes unitários com pytest
