name: PostgreSQL service example

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Escolha a versão do Python que deseja usar

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2  # ou qualquer outra biblioteca necessária

      - name: Connect to PostgreSQL
        run: python src/app.py  # Substitua 'script.py' pelo nome do seu script Python
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
