name: PostgreSQL service example

on: push

jobs:
  build:
    runs-on: macos-latest
    env:
      PGUSER: severinoapp_test
      PGPASSWORD: severinoapp_test
      PGHOST: localhost
      PGPORT: 5432  # Use a porta padrão ou a que você configurou
      PGDATABASE: severinoapp_test_db

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install PostgreSQL
        run: |
          brew install postgresql@16
          sleep 10  # Espera o serviço iniciar completamente
          brew services start postgresql@16
          sleep 10  # Espera o serviço iniciar completamente
          brew services list  # Verifica o status do PostgreSQL
          sleep 10  # Espera o serviço iniciar completamente

      - name: Configure PostgreSQL
        run: |
          psql -c "CREATE USER ${PGUSER} WITH PASSWORD '${PGPASSWORD}' CREATEDB;"
          psql -c "SELECT rolname FROM pg_roles;"
          psql -c "CREATE DATABASE IF NOT EXISTS ${PGDATABASE} OWNER ${PGUSER};"
          psql -c "\l"  # Lista todos os bancos de dados

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2
          pip install -r nrequirements.txt

      - name: Connect to PostgreSQL
        run: pytest
