name: PostgreSQL service example

on: push

jobs:
  build:
    runs-on: macos-latest
    env:
      PGUSER: severinoapp_test
      PGPASSWORD: severinoapp_test
      PGHOST: localhost
      PGPORT: 5432  # Use a porta padrão ou a que você configurou
      PGDATABASE: severinoapp_test_db

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Escolha a versão do Python que deseja usar

      - name: Install PostgreSQL
        run: |
          brew install postgresql
          brew services start postgresql
          sleep 5  # Espera o serviço iniciar completamente

      - name: Configure PostgreSQL
        run: |
          psql -c "CREATE ROLE ${PGUSER} WITH LOGIN PASSWORD '${PGPASSWORD}';"
          psql -c "CREATE DATABASE ${PGDATABASE} OWNER ${PGUSER};"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2  # ou qualquer outra biblioteca necessária
          pip install -r nrequirements.txt  # Instala as dependências do projeto

      - name: Connect to PostgreSQL
        run: pytest
