name: PostgreSQL service example

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Escolha a versão do Python que deseja usar

      - name: Install PostgreSQL
        run: |
          brew install postgresql
          brew services start postgresql

      - name: Configure PostgreSQL
        run: |
          export PGUSER=severinoapp_test
          export PGPASSWORD=severinoapp_test
          export PGHOST=localhost
          export PGPORT=5434
          export PGDATABASE=severinoapp_test_db
          echo "host all all 127.0.0.1/32 md5" >> /usr/local/var/postgres/pg_hba.conf
          echo "listen_addresses = '*'" >> /usr/local/var/postgres/postgresql.conf
          echo "port = 5434" >> /usr/local/var/postgres/postgresql.conf
          brew services restart postgresql

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2  # ou qualquer outra biblioteca necessária
          pip install -r nrequirements.txt # Instala as dependências do projeto

      - name: Connect to PostgreSQL
        run: pytest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5434
          POSTGRES_USER: severinoapp_test
          POSTGRES_PASSWORD: severinoapp_test
          POSTGRES_DB: severinoapp_test_db
