name: PostgreSQL service example

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Escolha a versão do Python que deseja usar

      - name: Install PostgreSQL
        run: |
          choco install postgresql --params '/Password:severinoapp_test'
          $env:PGUSER='severinoapp_test' # Usuário para autenticação
          $env:PGPASSWORD='severinoapp_test' # Senha para autenticação
          $env:PGHOST='localhost' # Host do servidor PostgreSQL
          $env:PGPORT='5434' # Porta padrão do PostgreSQL
          $env:PGDATABASE='severinoapp_test_db' # Nome do banco de dados
          & 'C:\Program Files\PostgreSQL\13\bin\psql.exe' -c "CREATE USER severinoapp_test WITH PASSWORD 'severinoapp_test';"
          & 'C:\Program Files\PostgreSQL\13\bin\psql.exe' -c "CREATE DATABASE severinoapp_test_db OWNER severinoapp_test;"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2  # ou qualquer outra biblioteca necessária
          pip install -r nrequirements.txt # Instala as dependências do projeto

      - name: Connect to PostgreSQL
        run: pytest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5434
          POSTGRES_USER: severinoapp_test
          POSTGRES_PASSWORD: severinoapp_test
          POSTGRES_DB: severinoapp_test_db