name: PostgreSQL service example

on: push

jobs:
  build:
    runs-on: windows-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: severinoapp_test
          POSTGRES_PASSWORD: severinoapp_test
          POSTGRES_DB: severinoapp_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Wait for PostgreSQL to be ready
        run: |
          sleep 10
          until pg_isready -h localhost -p 5432 -U severinoapp_test; do echo "Waiting for postgres..."; sleep 1; done

      - name: Set environment variables for PostgreSQL
        run: |
          echo "POSTGRES_USER=severinoapp_test" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=severinoapp_test" >> $GITHUB_ENV
          echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
          echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
          echo "POSTGRES_DB=severinoapp_test_db" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2
          pip install -r nrequirements.txt

      - name: Run tests
        run: pytest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
