name: PostgreSQL service example

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Download and install PostgreSQL
        run: |
          $url = "https://get.enterprisedb.com/postgresql/postgresql-13.2-1-windows-x64-binaries.zip"
          $output = "postgresql.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Path $output -DestinationPath C:\PostgreSQL
          Rename-Item -Path C:\PostgreSQL\postgresql-13.2-1-windows-x64-binaries -NewName PostgreSQL
          Remove-Item -Path $output

      - name: Set up PostgreSQL environment variables
        run: |
          setx /M PATH "$env:PATH;C:\PostgreSQL\bin"
          setx /M PGUSER severinoapp_test
          setx /M PGPASSWORD severinoapp_test
          setx /M PGHOST localhost
          setx /M PGPORT 5432
          setx /M PGDATABASE severinoapp_test_db

      - name: Initialize PostgreSQL
        run: |
          initdb -U postgres -A trust -E UTF8 -D "C:/PostgreSQL/data"
          pg_ctl start -D "C:/PostgreSQL/data" -l logfile
          psql -U postgres -c "CREATE USER severinoapp_test WITH PASSWORD 'severinoapp_test';"
          psql -U postgres -c "CREATE DATABASE severinoapp_test_db OWNER severinoapp_test;"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2
          pip install -r nrequirements.txt

      - name: Run tests
        run: pytest
        env:
          POSTGRES_USER: severinoapp_test
          POSTGRES_PASSWORD: severinoapp_test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: severinoapp_test_db
