name: PostgreSQL service example

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install PostgreSQL
        run: |
          choco install postgresql --params '/Password:severinoapp_test'
          setx /M PGUSER severinoapp_test
          setx /M PGPASSWORD severinoapp_test
          setx /M PGHOST localhost
          setx /M PGPORT 5432
          setx /M PGDATABASE severinoapp_test_db

      - name: Initialize PostgreSQL
        shell: powershell
        run: |
          & "C:\Program Files\PostgreSQL\13\bin\psql.exe" -U postgres -c "CREATE USER severinoapp_test WITH PASSWORD 'severinoapp_test';"
          & "C:\Program Files\PostgreSQL\13\bin\psql.exe" -U postgres -c "CREATE DATABASE severinoapp_test_db OWNER severinoapp_test;"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2
          pip install -r nrequirements.txt

      - name: Run tests
        run: pytest
        env:
          POSTGRES_USER: severinoapp_test
          POSTGRES_PASSWORD: severinoapp_test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: severinoapp_test_db
