name: PostgreSQL service example

on: push

jobs:
  build:
    runs-on: windows-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: severinoapp_test
          POSTGRES_PASSWORD: severinoapp_test
          POSTGRES_DB: severinoapp_test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Wait for PostgreSQL to be ready
        run: |
          Write-Host "Waiting for PostgreSQL to start..."
          & 'C:\Program Files\PostgreSQL\13\bin\pg_isready.exe' -h localhost -p 5432 -U severinoapp_test -d severinoapp_test_db -t 60

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2
          pip install -r nrequirements.txt

      - name: Run tests
        run: pytest
        env:
          POSTGRES_USER: severinoapp_test
          POSTGRES_PASSWORD: severinoapp_test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: severinoapp_test_db
