name: PostgreSQL service example

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: ikalnytskyi/action-setup-postgres@v6 
        with:
          username: severinoapp_test
          password: severinoapp_test
          database: severinoapp_test_db
          port: 5434
        id: postgres

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2  # ou qualquer outra biblioteca necessária
          pip install -r nrequirements.txt # Instala as dependências do projeto

      - name: Connect to PostgreSQL
        run: pytest
        env:
          PGUSER: severinoapp_test
          PGDATABASE: severinoapp_test_db
          PGPORT: 5434  # Default PostgreSQL port
          PGPASSWORD: severinoapp_test
